### PR TITLE
Fix errors for the new react-native-fs versions and improve code a little bit

### PR DESCRIPTION
**Pull request by scerelli**

### CODE REVIEW

**Comment by jayesbe** [comment]
@scerelli Thanks!  Looks good to me. I will merge it in today or by tomorrow and tag it as 1.2

**Comment by scerelli** [comment]
Ok is not that easy. What i suggest here is to wrap the image inside a View and give to it a `width` and `height`equal the image so we can place the loader right in the middle of the box.

**Comment by jayesbe** [comment]
@scerelli I merged your changes into a new branch for version 1.2.0. Thanks again. closing this PR.

**Comment by jayesbe** [comment]
@scerelli  I just saw your comment there in the middle regarding wrapping the image in a View.  Perhaps that was meant for an issue?

**Pull request closed without merging**
