### PR TITLE
Improved readme and fixed crash for empty image source

### PR DESCRIPTION
**Pull request by eugenehp**
Fixed crashes when `uri` is empty: 
```jsx
<CacheableImage source={{uri:''}}/>
```

### CODE REVIEW

**Comment by jayesbe** [comment]
@eugenehp I'm going to cherry pick your changes to leave out Nathan's changes.

**Comment by eugenehp** [comment]
@jayesbe sounds good. let me know if you need any help with it.

**Comment by jayesbe** [comment]
@eugenehp added your readme changes and empty source fix. I left out nathan's changes for now.. seeking a better option.

**Comment by jayesbe** [comment]
Yup already pushed 1.4.3

**Comment by eugenehp** [comment]
Awesome!

**Pull request closed without merging**
